#+TITLE: InklingReader to-do list

* Features

  In this category, possible new features are described. Feel free to implement
  any of them.

** [ ] Research the 'online-mode' option

   In the user manual 'online-mode' is mentioned. According to the manual, 
   pen strokes can be directly received by the computer when the receiver
   is connected to the computer.

   Recent developments have enabled a renewed effort of bringing this 
   feature to InklingReader. Although the best solution would be to
   get a kernel driver so this option can be used system-wide, the current
   efforts are aimed towards understanding the USB communication.

** [ ] Add gettext support to the program to allow translations.
** [ ] Handwriting recognition
       
   The sketches can contain text. Ideally, this handwriting should be
   converted to a plain-text file, or a LibreOffice or PDF document.

** [ ] Coloring individual strokes
       
   Providing basic editing capabilities like changing stroke colors and
   stroke thickness makes life easier for those who don't want to work
   with a full-blown editor like Inkscape.

   There has been an Inkscape extension for a while now that seems to be
   very mature. 

** [-] Give the choice for different paper backgrounds.

   PARTIAL FIX: Background colors can be specified.

** [X] Make a layer a different color when the user presses the "new layer" 
** [X] Inkscape layering support
** [X] Handle pressure data correctly.
** [X] Add a command-line option to disable pressure data and set a fixed 
** [X] Ability to merge files into one.
** [X] Get all features to work on Windows as well.
*** [X] Compile for Windows
*** [X] Convert a file with the Windows binary
*** [X] Convert all files in a directory with the Windows binary
*** [X] Use the graphical user interface with the Windows binary
**** [X] Open a file
***** [X] Export as PDF
***** [X] Export as PNG
***** [X] Export as SVG


* Documentation

  In this category, documentation efforts are described. Even if you don't
  have programming skills, these tasks would be fairly easy to pick up.

** [ ] Update the current user guide and describe all features.
** [ ] Document the WPI file format.
** [ ] Document the USB communication.
** [ ] Create a Inkling-drawn demo drawing to use in screenshots.
